apiVersion: v1
kind: Pod
metadata:
  name: immich
  labels:
    app: immich
  annotations:
spec:

  ## Volume definitions
  volumes:
    - name: immich-data-host
      hostPath:
        ## Equivalent of UPLOAD_LOCATION in docker-compose
        path: /path/to/immich/data
        type: Directory
    - name: immich-psql
      hostPath:
        path: /path/to/immich/model-cache
        type: Directory
      name: immich-model-cache-host
      persistentVolumeClaim:
        claimName: immich-psql
    - name: immich-redis-host
      hostPath:
        path: /path/to/immich/redis
        type: Directory

  ## Container definitions  
  containers:
    ## Starting from v1.106.1 the separate microservices
    ## container is no longer necessary
    - name: server
      image: ghcr.io/immich-app/immich-server:v2.4.1
      envFrom:
      - configMapRef:
          name: immich-config
          optional: false
      securityContext:
        capabilities:
          drop:
          - CAP_MKNOD
          - CAP_NET_RAW
          - CAP_AUDIT_WRITE
      volumeMounts:
      - mountPath: /usr/src/app/upload
        name: immich-data-host
      - mountPath: /nextcloud/nc-user
        name: nextcloud-nc-user
        readOnly: true

    - name: machine-learning
      image: ghcr.io/immich-app/immich-machine-learning:v2.4.1
      envFrom:
      - configMapRef:
          name: immich-config
          optional: false
      securityContext:
        capabilities:
          drop:
          - CAP_MKNOD
          - CAP_NET_RAW
          - CAP_AUDIT_WRITE
      volumeMounts:
      - mountPath: /usr/src/app/upload
        name: immich-data-host
      - mountPath: /cache
        name: immich-model-cache-host
    
    - name: psql
      image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
      resource: {}
      securityContext:
        capabilities:
          drop:
          - CAP_MKNOD
          - CAP_NET_RAW
          - CAP_AUDIT_WRITE
      volumeMounts:
      - mountPath: /var/lib/postgresql/data
        name: immich-psql
      env:
      - name: POSTGRES_USER
        valueFrom:
          configMapKeyRef:
            name: immich-config
            key: DB_USERNAME
      - name: POSTGRES_PASSWORD
        valueFrom:
          configMapKeyRef:
            name: immich-config
            key: DB_PASSWORD
      - name: POSTGRES_DB
        valueFrom:
          configMapKeyRef:
            name: immich-config
            key: DB_DATABASE_NAME
      - name: POSTGRES_INITDB_ARGS
        value: "--data-checksums"
      args: ["-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

    - name: redis
      image: docker.io/valkey/valkey:9@sha256:fb8d272e529ea567b9bf1302245796f21a2672b8368ca3fcb938ac334e613c8f
      args:
      - redis-server
      - --save
      - 60
      - 1
      - --loglevel
      - warning
      resources: {}
      securityContext:
        capabilities:
          drop:
          - CAP_MKNOD
          - CAP_NET_RAW
          - CAP_AUDIT_WRITE
      volumeMounts:
      - mountPath: /data
        name: immich-redis-host

  restartPolicy: Always
status: {}
